### ISSUE TITLE
Option to test internet connexion? 

### ISSUE THREAD

**Issue by abichat** [jhollist/dadjoke#1]
I have `dadjoke::groan()` in my .Rprofile and when I'm not connected to internet, I just don't have the joke but it's fine.

However, when I compile a markdown file, it stops the execution... 

![](https://s14.postimg.cc/clw2s1gpd/Capture_d_e_cran_2018-04-27_a_09.31.10.png)

Maybe add an option to test if internet connexion is available is a good idea?

```
try(is.character(RCurl::getURL("icanhazdadjoke.com"))) == TRUE
```

**Comment by jhollist** [comment]
Thanks for the suggestion!  Should work now.
