### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by jhollist** [jhollist/dadjoke#3]
- [x] Add Brett Landgdon as cph
- [x] Add search API endpoint
- [x] Add specific dadjoke ID endpoint
- [x] Add image endpoint
- [x] Add custom user agent

**Comment by brettlangdon** [comment]
- Use a custom user agent string.
  - https://icanhazdadjoke.com/api#custom-user-agent

Thank you for writing this! :)

**Comment by jhollist** [comment]
Hoping to spend some time on updating the package to reflect the enhancements you made to the API.  Will get the user agent taken care of first!  

And thank you for the API!

**Comment by jhollist** [comment]
Just made the change to the user agent.  I **think** it is working correctly!

**Comment by brettlangdon** [comment]
User agent looks good to me! :+1:

**Comment by jhollist** [comment]
These to dos are done!
